### PR TITLE
More improvements. (😳)

### PR DESCRIPTION
**Pull request by MatthewTGM**
+ Rewrote build.gradle.
- Downgraded to Gradle 4.8.1 (There's practically no benefit to using newer version, to my knowledge at least.)

### CODE REVIEW

**Comment by isXander** [comment]
When your 'improvement' is downgrading to ancient gradle version

**Comment by isXander** [comment]
Also useless dependency complication

**Comment by isXander** [comment]
I'm guessing the only reason you downgraded was because of mixin gradle but there are forks for that!

**Comment by ChachyDev** [comment]
why in the world would you go back to gradle 4.8.1

**Comment by MatthewTGM** [comment]
> Also useless dependency complication

More automation for annotation processors and module exclusion

> I'm guessing the only reason you downgraded was because of mixin gradle but there are forks for that!

I downgraded because IntelliJ was spitting in my face.

> why in the world would you go back to gradle 4.8.1

For use of old, deprecated things.

**Comment by DeDiamondPro** [comment]
I really do not see the advantages here:
1. downgrading gradle version
2. build times go up
3. its a build.gradle you basically don't touch it unless you need a new lib which is rarely.

**Pull request closed without merging**
