### PR TITLE
Clean up project

### PR DESCRIPTION
**Pull request by wyvest**
Did some stuff
Changelog
- Remove unnecessary jvm arguments being added
- Add mod name
- Rename hycord.class to HyCord.class
- Replace NetworkUtils with WebUtil and UUIDUtil
- Add capitalization in the s in macOS
- Make HyCord update notification show when Forge finishes loading instead of when a GUI is opened
- Changed UpdateChecker#openTab to a Unit
- Move ModCoreInstaller to club.sk1er.modcore

### CODE REVIEW

**Review by DeDiamondPro — CHANGES_REQUESTED** [review]
Could you please revert the changes related to NetworkUtils since I plan on moving away from modcore soon and adding more dependencies to it wouldn't be a smart move.

**Comment by wyvest** [comment]
> Could you please revert the changes related to NetworkUtils since I plan on moving away from modcore soon and adding more dependencies to it wouldn't be a smart move.

i will do this tomorrow

**Comment by DeDiamondPro** [comment]
> > Could you please revert the changes related to NetworkUtils since I plan on moving away from modcore soon and adding more dependencies to it wouldn't be a smart move.
> 
> i will do this tomorrow

okay, thanks

**Comment by wyvest** [comment]
just use #10

**Pull request closed without merging**
